# Generated by Django 4.1.7 on 2023-06-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0030_rename_product_orderhistory_product_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="payment",
            field=models.BooleanField(default=False),
        ),
    ]
