# Generated by Django 4.1.7 on 2023-06-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0031_orderhistory_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="order_id",
            field=models.CharField(default="default", max_length=100),
        ),
    ]
