# Generated by Django 4.1.7 on 2023-06-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0032_orderhistory_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="payment_id",
            field=models.CharField(default="default", max_length=100),
        ),
    ]
